[github]
username = "Prakash-1619"   # your GitHub username
token = "g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"  # your classic PAT
repo = "V_2.2"              # your repository name
branch = "main"             # the branch to push to
